-- Migration 014 — admin mailbox client
SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS email_accounts (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 email_address VARCHAR(190) NOT NULL UNIQUE, display_name VARCHAR(190) NOT NULL,
 imap_host VARCHAR(190) NOT NULL, imap_port SMALLINT UNSIGNED NOT NULL DEFAULT 993, imap_encryption VARCHAR(10) NOT NULL DEFAULT 'ssl',
 smtp_host VARCHAR(190) NOT NULL, smtp_port SMALLINT UNSIGNED NOT NULL DEFAULT 587, smtp_encryption VARCHAR(10) NOT NULL DEFAULT 'tls',
 password_encrypted TEXT NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
